### ISSUE TITLE
All chatbox messages are visible by every logged-in user

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-issues#137]
I'm concerned that users might discuss sensitive information in this chatbox.
In addition it shows (non sensitive) messages about the import of data sets, regardless of the access level.

Do you think this chat box is useful for users @satagopam7 ? We might want to remove it, if not.

![Screenshot 2020-01-17 at 10 18 59](https://user-images.githubusercontent.com/11333940/72599875-cd9c7980-3912-11ea-922e-80b12a0b8701.png)

**Comment by peterbanda** [comment]
I would filter out system messages (from Ada itself) for ordinary users and keep those for admins only
