### ISSUE TITLE
Rework filter represenation

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-issues#140]
Requested by @satagopam7: the filter representation needs to be reworked.
It is using developer specific symbols like != and is hard to understand when there are many filter arguments.

**Comment by peterbanda** [comment]
Should propose lame names for the operators:
- equal                    - currently as "**=**"
- not equal              - currently as "**!=**"
- regex equal          - currently as "**like**"
- regex not equal    - currently as "**not like**"
- in                          - currently as "**in**"
- not in                    - currently as "**nin**"
- greater                 - currently as "**>**"
- greater or equal   - currently as "**>=**"
- less                      - currently as "**<**"
- less or equal        - currently as "**<=**"

**Comment by peterbanda** [comment]
Note that only the rendering of the operators should be changed (not their internal "toString" representation)
