### ISSUE TITLE
What is the logic behind Column/Bar chart sequential order?

### ISSUE THREAD

**Issue by ghoshted** [ada-discovery/ada-issues#178]
Can anyone please explain why the column order are like this?

![image](https://user-images.githubusercontent.com/509036/125826538-fc397979-640f-4f86-a5ad-4fcb441bd13c.png)

For that chart I would expect ..the columns orders will be Visit 0 to Visit 6..  but it is Visit 0, Visit 6, Visit 1, Visit 2, Visit 3.
Nor it is sorted on the variables values, neither total count (Ada usually follow sorted order on numeric count, that is also very problematic) 

If I change the variable values Visit 0 to only 0 (and so on), the chart becomes like this 

![image](https://user-images.githubusercontent.com/509036/125826496-ca3d1299-eddf-4bef-982e-8bb1b2b2432f.png)

:exploding_head:

**Comment by LBolzani** [comment]
Good afternoon Soumya,

I did an update on a new branch to fix this problem. As soon as possible I'll deploy on the test server then you can check/test the feature.

You can enable the feature when you're going to create a new chart in the _Edit view settings_, there is a new checkbox called _Order by Field_

<img width="621" alt="WidgetSpec" src="https://user-images.githubusercontent.com/84960775/127497980-223d0ec2-0682-47a9-bc7f-3e40d1633bba.png">

Luca

**Comment by LBolzani** [comment]
Hello Soumya, you can test the feature at this address https://10.240.16.149/ .

Luca

**Comment by ghoshted** [comment]
Yes .. I will 🚩🚩

**Comment by LBolzani** [comment]
@soumyabrataghosh did you have time to check the feature?

**Comment by sherzinger** [comment]
ping @soumyabrataghosh

**Comment by ghoshted** [comment]
today .. I will

**Comment by LBolzani** [comment]
@soumyabrataghosh I need that you verify the issue. Could you give me a feedback?

**Comment by ghoshted** [comment]
@LBolzani I don't have access to any dataset on https://10.240.16.149/ ... how to check?

**Comment by sherzinger** [comment]
@soumyabrataghosh that was an unintended side effect of moving the permission system into Keycloak. I added you to the admin role for the test client. Can you please check again?

**Comment by ghoshted** [comment]
Tonight again.

**Comment by sherzinger** [comment]
@soumyabrataghosh please? :-)

**Comment by sherzinger** [comment]
Reporter didn't respond. Issue considered solved for now.

**Comment by ghoshted** [comment]
Agreed.
