### ISSUE TITLE
Filter gets deleted from widget dialogue box

### ISSUE THREAD

**Issue by ghoshted** [ada-discovery/ada-issues#180]
When I try to edit a widget in a view, the filter is automatically removed each time when the dialogue box is opened. Probably a JavaScript bug.

**Comment by ghoshted** [comment]
https://user-images.githubusercontent.com/509036/127484297-f027b41b-1102-437e-a56c-af68065d4bfe.mov

**Comment by sherzinger** [comment]
likely related to #185

**Comment by LBolzani** [comment]
Good morning Soumya, you can test the bug fix at https://10.240.16.149/ .

Luca

**Comment by LBolzani** [comment]
@soumyabrataghosh did you have time to check the feature?

**Comment by sherzinger** [comment]
@soumyabrataghosh Please have a look

**Comment by sherzinger** [comment]
Reporter didn't respond. Issue considered solved for now.

**Comment by ghoshted** [comment]
@sherzinger @LBolzani .. It seems this bug is NOT resolved .. 

https://user-images.githubusercontent.com/509036/137904937-10765d15-4daf-49bf-abc9-84a67bb0385d.mov

**Comment by LBolzani** [comment]
@soumyabrataghosh where did you test it?

**Comment by sherzinger** [comment]
Slight misunderstanding here. The filter id was replaced with the filter description, but the disappearing wasn't resolved.
Luca is on it

**Comment by ghoshted** [comment]
@LBolzani https://10.240.16.149/dataSets/dataviews/getAndShowView/6023a5626200000929226a46?dataSet=open.iris

**Comment by ghoshted** [comment]
@LBolzani any update on this?

**Comment by LBolzani** [comment]
@soumyabrataghosh I did a fix, you can test it in the next deployment that I'm gonna make in ada-test instance.

**Comment by LBolzani** [comment]
Hello @soumyabrataghosh you can test the fix at: https://10.240.16.149/

**Comment by LBolzani** [comment]
@soumyabrataghosh could you give me a feedback about this fix?

**Comment by ghoshted** [comment]
This is solved.
