### ISSUE TITLE
Cannot choose an empty column to define a graph

### ISSUE THREAD

**Issue by xinhuiwang** [ada-discovery/ada-issues#182]
is it possible to choose an empty column to define a graph? this could help to prepare a graph that will become useful at a later stage (i.e. updated data).

**Comment by ghoshted** [comment]
@xinhuiwang You can add such graphs in the view, but it will be hidden from the view if there is no data. When the data is available, it will appear. This also true in the case of filter, when a filter causes no data, the graphs disappear from the view. (This is a #dataviz problem, need to bee discussed @sherzinger)

**Comment by sherzinger** [comment]
Depending on the graph library used this will cause very ugly results or outright fail, which is why the graphs are hidden. If you need a placeholder please use dummy values. We might deal with this differently in the future, but it is not a priority.
