### ISSUE TITLE
add some commonly used mathematical  function/ formula

### ISSUE THREAD

**Issue by xinhuiwang** [ada-discovery/ada-issues#183]
is it possible to add some basic mathematical function/ formula (e.g. “sum(var,var2)“) for numerical values?

**Comment by ghoshted** [comment]
Runnable are there.
But I would recommend that you do this at the ETL level, not at the visualisation level.

**Comment by sherzinger** [comment]
The idea is nice, but the feature is out of scope for the moment.
Please do it in the ETL, like Soumya suggested.
