### ISSUE TITLE
Cannot add Filter or Ids when generate views

### ISSUE THREAD

**Issue by xinhuiwang** [ada-discovery/ada-issues#184]
the Filter or Ids could not be added to View
![Screenshot 2021-07-30 at 09 59 02](https://user-images.githubusercontent.com/20066309/127621204-4e32fb2f-d826-435c-b8d0-d8f7cbac4c3c.png)

**Comment by ghoshted** [comment]
@xinhuiwang Have you created the filter? You need to create the filter, save and name it from the view, then only you will find it here.

https://user-images.githubusercontent.com/509036/127639516-13e79bf8-374c-4610-af0a-c191d996bb9c.mov

**Comment by xinhuiwang** [comment]
thanks！the problem was solved!

**Comment by xinhuiwang** [comment]
thanks! the problem was solved! @soumyabrataghosh
