### ISSUE TITLE
Figure title lost after updating.

### ISSUE THREAD

**Issue by xinhuiwang** [ada-discovery/ada-issues#185]
Editing a graph and its title -> title is lost after updating.

**Comment by ghoshted** [comment]
This is a bug, and may be related to #180  @sherzinger

**Comment by sherzinger** [comment]
confirmed

**Comment by LBolzani** [comment]
Good morning Xinhui, you can test the bug fix at https://10.240.16.149/ .

Luca

**Comment by LBolzani** [comment]
@xinhuiwang did you have time to check the feature?

**Comment by xinhuiwang** [comment]
@LBolzani Sorry for the later response and I am invacation! the problem seems still there. I change the plot, then the title is missing again.

**Comment by LBolzani** [comment]
Good morning @xinhuiwang I think you have tested directly in production. The fix is not still available in prod.
Could you try here: https://10.240.16.149/ 

I remain at your disposal for any further information.

Luca

**Comment by sherzinger** [comment]
@xinhuiwang please have a look. We're still waiting for your response.

**Comment by xinhuiwang** [comment]
> @xinhuiwang please have a look. We're still waiting for your response.

Hi, @sherzinger thanks! Luca and I already check it and it is totally fine! the issue is solved.

**Comment by sherzinger** [comment]
Ok, we will update the Ada instances soon at the next release.

**Comment by sherzinger** [comment]
solved!
