### ISSUE TITLE
Use OIDC role information to map to local permissions

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-issues#189]
**Description:**
Keycloak will provide roles like `ACCESS::<DataSetId>`, e.g. `ACCESS::123-foo-bar-456`.
If a user has this role, they should automatically get read-only access to the local dataset with the id `123-foo-bar-456`.
This id might be different from the actual human readable dataset name, so the model might have to be expanded to account for this.

If the user looses this role, they should no longer have access to that dataset.

**Notes:** 
OIDC roles are stored in ID token, access token, and /userinfo endpoint.

/userinfo is the preferred way of checking if a user has a certain role, because it is instant, but if that's too difficult to implement, please use ID token, which is correct for as long as the token is valid (1 day I think).

**Comment by LBolzani** [comment]
Hello Sascha, 
maybe have I to create a migration script to map local dataset name with data catalog global id?
Right now inserting is available only by user interface “Data Settings”.

**Comment by sherzinger** [comment]
@LBolzani not all datasets will have an ID, so it is optional.
I think it's fine to specify them manually one by one.

**Comment by LBolzani** [comment]
Good morning @sherzinger, you can test the feature at https://10.240.16.149/ .

Luca

**Comment by LBolzani** [comment]
Hello @sherzinger could we call keycloak admin role for ada: ROLE_ADA_ADMIN ?

**Comment by sherzinger** [comment]
sure :-)

**Comment by LBolzani** [comment]
Good morning @sherzinger I've updated the feature with our last considerations.
You can test at https://10.240.16.149/ as well.
Don't forget to add ROLE_ADA_ADMIN to your Keycloak account.

**Comment by sherzinger** [comment]
solved!
