### ISSUE TITLE
Change minimize/maximize icons to collapse/extend icons to better reflect their functionality

### ISSUE THREAD

**Issue by ghoshted** [ada-discovery/ada-issues#192]
This minimise/maximise buttons do not work.

![image](https://user-images.githubusercontent.com/509036/134022817-e2acc4f8-aa59-4be1-9176-35d95fec5c22.png)

Instance: biomap-ada.lcsb.uni.lu

**Comment by ghoshted** [comment]
Any comment on this @sherzinger?

**Comment by sherzinger** [comment]
Confirmed

**Comment by peterbanda** [comment]
@soumyabrataghosh the widget on the left you are referring to is a tree and you have no nodes (categories) so there is nothing to collapse/expand.

**Comment by sherzinger** [comment]
Or he understood them the same as me: fit content vs minimise it. I also thought those buttons are buggy. @soumyabrataghosh do you meant to expand a tree or see the full field names?

**Comment by peterbanda** [comment]
Btw. the whole area is horizontally (as well as vertically) scrollable so it's always possible to see full field names/labels...

**Comment by sherzinger** [comment]
Considering that 3 different people interpreted those icons wrong, I think a change is in order. They do work, but they don't minimize/maximize, they collapse/extent. I changed the issue title accordingly.

**Comment by peterbanda** [comment]
Well, the buttons' (current) tooltips are `Collapse All`and `Expand All` :)

**Comment by LBolzani** [comment]
Hello @soumyabrataghosh  I did an update regarding this issue, icons appears only when there are folders/ancestors and not in presence of only tree's leaves.
You can test it at: https://10.240.16.149/

**Comment by sherzinger** [comment]
<img width="262" alt="Screenshot 2021-11-16 at 15 00 14" src="https://user-images.githubusercontent.com/11333940/141999079-bdb51ff0-3407-4805-9f32-775cac6efe9f.png">


the icons should be next to each other ideally. In another issue maybe we can also discuss the resizability of that section. It's not very useful with long variable names.

**Comment by sherzinger** [comment]
And maybe increase the font-size of the icons a tad. They seems a bit too small

**Comment by ghoshted** [comment]
I would prefer making it a single toggle button like below.. because the action of both buttons is all or none .. 

![image](https://user-images.githubusercontent.com/509036/142053401-1be6007f-92ea-4aa7-8337-eee7a86fba99.png)

**Comment by LBolzani** [comment]
@sherzinger I increased the icon size, regarding the position usually they stay horizontally, did you decrease window's size? If yes it's normal. @soumyabrataghosh I prefer to stay with two buttons.

**Comment by sherzinger** [comment]
![Screenshot 2021-11-18 at 08 43 24](https://user-images.githubusercontent.com/11333940/142373173-3111f706-06c9-4e11-a130-709a31d3be26.png)

Really minor, but could you please alter the settings slightly like this?
The current oneslooks a bit stretched and pixelated on my screen at least.
