### ISSUE TITLE
Redirect to specific view URL after login

### ISSUE THREAD

**Issue by ghoshted** [ada-discovery/ada-issues#193]
Situation: Someone shares a specific Ada view link to others. Other person is not logged in, she tries to open the link and it asks her to login. Once she sign-in, she is not forwarded to the specific view link. 
Can we solve this?

**Comment by ghoshted** [comment]
@sherzinger This is a requirement of Biomap project .. as we are linking Ada to Catalog .. 

![image](https://user-images.githubusercontent.com/509036/140322759-09b5b500-6d1c-4222-a3cd-5bffe99840fa.png)

**Comment by sherzinger** [comment]
@LBolzani can you estimate the effort it takes to do this? I agree with @soumyabrataghosh that this is a bit painful. I think you fixed the same issue already in Podium a while ago, no?

**Comment by LBolzani** [comment]
Good morning, I'll check, I'll come back as soon as possible

**Comment by LBolzani** [comment]
@soumyabrataghosh , @sherzinger 
I did a check. I think with the new deployment there is no problem. With a specific link after login the user is redirected to the selected link.

I've tried with a couple of ones:
- https://ada.parkinson.lu/dataSets/getView?dataViewId=58327e00ea0000a901239216&dataSet=lux_park.clinical
- https://ada.parkinson.lu/dataSets/getView?dataViewId=5e998721c80000f06e41b793&dataSet=synpuf.care_site

Luca

**Comment by ghoshted** [comment]
Great @LBolzani ..

**Comment by sherzinger** [comment]
Issue seems to be fixed. Let's include it in the next release alongside a few other changes. Thank you @LBolzani

**Comment by sherzinger** [comment]
Sorry, I just realized this is already the current version. Well, even better :-)

**Comment by peterbanda** [comment]
well, this has always worked

**Comment by ghoshted** [comment]
This has not worked in the older version in Biomap instance at least

**Comment by peterbanda** [comment]
Hey there. I actually had dozens of bookmarks for production Adas so relied on it quite heavily. I've just tried a local (older) version without OIDC and it worked. Anyway, it's too late to figure out what exactly was wrong.... have a nice weekend

**Comment by ghoshted** [comment]
Maybe it was some LUMS login issue .. when the user was already logged in..
the url worked .. but not otherwise ..
better it is not there anymore .. working as expected
