### ISSUE TITLE
Remove LDAP and local account creation

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-issues#195]
@LBolzani  We can completely remove this and all associated functionality (like LDAP) from our branch now that we have oidc

<img width="476" alt="Screenshot 2021-11-03 at 11 30 43" src="https://user-images.githubusercontent.com/11333940/140044906-e26beb39-2838-4f35-9120-85a455163f79.png">

Same goes for creating local accounts:
<img width="218" alt="Screenshot 2021-11-03 at 11 31 20" src="https://user-images.githubusercontent.com/11333940/140045013-372d611d-96d1-433d-88a1-f19796ed636a.png">

**Comment by LBolzani** [comment]
Hello @sherzinger you can test the fix at https://10.240.16.149/

**Comment by sherzinger** [comment]
I think we can remove those as well:

<img width="235" alt="Screenshot 2021-11-16 at 14 58 36" src="https://user-images.githubusercontent.com/11333940/141998809-31b1077b-e245-462a-8c25-bf0357df5b58.png">

@LBolzani did you check if the server still starts without the LDAP config?
Ideally we can completely remove this from all servers.

**Comment by LBolzani** [comment]
I removed those functionalities, in the patch, LDAP will be disabled by default

**Comment by sherzinger** [comment]
looking good! Thank you @LBolzani
