### ISSUE TITLE
Investigate multiple account bug

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-issues#196]
<img width="771" alt="Screenshot 2021-11-03 at 11 32 53" src="https://user-images.githubusercontent.com/11333940/140045208-0ebfbdbc-e688-4dc4-8ed1-97b4e15f33ff.png">

https://immuniverse-ada.lcsb.uni.lu/users/all

**Comment by LBolzani** [comment]
Hello @sherzinger I did a fix, in order to track the bug I added more logs.
I created a db script to delete duplicates.
I was quite able to reproduce the bug, but let's see in prod.

The update is available at https://10.240.16.149/

**Comment by sherzinger** [comment]
Okay, I'm gonna keep this open until we checked it in immuniverse at least, ok?

**Comment by LBolzani** [comment]
Ok sounds good 👍

**Comment by sherzinger** [comment]
@LBolzani could you check if the issue appeared on any instance again? If not, we can probably close this

**Comment by sherzinger** [comment]
An account on ada.parkinson.lu was not migrated successfully, but instead a new account was generated.
Please contact me for more details when you're back :-)

**Comment by LBolzani** [comment]
Good afternoon @sherzinger I've checked the problem regarding ada.parkinson.lu account.

The issue is due to the discrepancy between what we're receiving from oidc provider and what is present in local db yet.
Maybe we can do a meeting I can show in details what it happened.

Luca

**Comment by sherzinger** [comment]
solved as discussed
