### ISSUE TITLE
Import label's name automatically

### ISSUE THREAD

**Issue by LBolzani** [ada-discovery/ada-issues#209]
Create a view or a modal in order to permit automatically import for label's name in dictionary.
Maybe a csv with two columns.
Ex.:
- First column variable name;
- Second column label name.

**Comment by LBolzani** [comment]
Hello @sherzinger the feature is available at https://10.240.16.149/ in "Select a study" > Dictionary

**Comment by sherzinger** [comment]
@soumyabrataghosh would you or Shoaib mind testing this one? Just to make sure this is what you guys need

**Comment by ghoshted** [comment]
@sherzinger Yes I saw that feature .. super nice.. it will be great if there is an option to download the current dictionary template of the dataset in `csv`.. so people can change it there and upload it back

**Comment by sherzinger** [comment]
@LBolzani would you mind adding that too? That's a good suggestion I think

**Comment by LBolzani** [comment]
@sherzinger the export option is present yet on the top right corner

**Comment by ghoshted** [comment]
He he .. I always thought that they are for the data .. my bad .. yes it is already there 
Can we make it more obvious? and filtered/json etc does not make sense to me here.. but may be I'm wrong

![image](https://user-images.githubusercontent.com/509036/155142314-3e3defa9-ae75-47cb-a809-df62fd5a10ca.png)

**Comment by sherzinger** [comment]
@LBolzani thank you, I didn't know. Could you check if you can remove everything except of the `export all as CSV` ?
Only if it's not a lot of work

**Comment by LBolzani** [comment]
Ok I'll check 👍

**Comment by LBolzani** [comment]
Modified export button:
<img width="256" alt="Screenshot 2022-02-24 at 15 29 50" src="https://user-images.githubusercontent.com/84960775/155549670-f1dbd2a4-3605-4a08-9dc8-ab03fc300d25.png">

Update available at https://10.240.16.149/

**Comment by ghoshted** [comment]
@LBolzani Can we import Category as well?

**Comment by sherzinger** [comment]
@soumyabrataghosh That's a different feature, so not for the moment. But if it is needed we can discuss this.
