### ISSUE TITLE
Remove Ada logo or make it an option

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-issues#212]
We're not allowed to show unapproved logos. Replace this with text please:

<img width="165" alt="Screenshot 2022-02-16 at 13 31 35" src="https://user-images.githubusercontent.com/11333940/154265016-58dcf85c-1269-4b87-a2a9-e518c0a702b8.png">

**Comment by LBolzani** [comment]
Hello @sherzinger you can test at https://10.240.16.149/

**Comment by sherzinger** [comment]
fixed, thank you Luca
