### ISSUE TITLE
Stop horizontal autoscroll on the index page of Ada

### ISSUE THREAD

**Issue by sherzinger** [ada-discovery/ada-issues#216]
This is a problem with people for disabilities.

@LBolzani high prio because this comes from the communication department. We need this to proceed with the publication request.

**Comment by LBolzani** [comment]
Hello @sherzinger it's not clear for me what I have to update. Could you make me a screenshoot?

**Comment by sherzinger** [comment]
@LBolzani  this one

<img width="1247" alt="Screenshot 2022-03-07 at 11 59 27" src="https://user-images.githubusercontent.com/11333940/157018711-92c61767-261b-4c75-ac97-0909dcad90b8.png">

**Comment by sherzinger** [comment]
it scrolls horizontally automatically. The request is to stop this from happening basically

**Comment by LBolzani** [comment]
Ok, it's the automatic carousel. If I understood right.

Thank you.

**Comment by LBolzani** [comment]
Hello @sherzinger an update is available at https://10.240.16.149/
